# Generated by Django 4.2.6 on 2023-11-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_bank", "0001_initial"),
        ("core_user", "0003_alter_user_created_at_alter_user_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="banks_liked",
            field=models.ManyToManyField(related_name="liked_by", to="core_bank.bank"),
        ),
    ]
