# Generated by Django 4.2.6 on 2023-12-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_user", "0004_user_banks_liked"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
