# Generated by Django 4.2.6 on 2023-11-19 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core_bank", "0001_initial"),
        ("core_document", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="bank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core_bank.bank",
            ),
        ),
    ]
