name: Test frontend

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install Dependencies
        run: npm ci
      - name: Lint Code
        run: |
          # Replace the linting command with the appropriate one for Next.js
          # Example: eslint . 
          # You might need to adjust this command based on your linting setup
          npm run lint
        continue-on-error: true
      - name: Run Tests
        run: |
          # Replace the test command with the appropriate one for Next.js
          # Example: npm test
          # You might need to adjust this command based on your testing setup
          npm test
        continue-on-error: true
